name: tada
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=1.12.1
  - torchvision=0.13.1
  - torchaudio=0.12.1
  - cudatoolkit=11.6
#  - matplotlib=3.5.2
  - jupyter=1.0.0
  - pip
